### ISSUE TITLE
Not actually an issue, a question

### ISSUE THREAD

**Issue by jwelker9** [ricmik/AzureAD-PrivilegedAccessGroups#1]
Hey there @ricmik,

Sorry  to open an issue but hoping to get a hold of you. I'm doing a lot of PowerShell PIM work right now and have run into a blocker I was hoping to get your opinion on. Use Dev tools I also discovered in the past the "https://api.azrbac.mspim.azure.com" endpoint. 

I was able to pull down a token for it using your scripts, but I'm specifically trying to take advantage of the below call:

https://api.azrbac.mspim.azure.com/api/v2/privilegedAccess/azureResources/roleAssignments/exportWithChildren?`$expand=subject,roleDefinition(`$expand=resource)&`$filter=(roleDefinition/resource/id eq 'xxxxxx-xxxxxx-xxxxxx')

If you go to PIM > Azure Resources > select any resource > Assignments > Export > select Export all members, it makes the above call.

The problem is even after grabbing the token I'm not able to successfully complete this call "Attempted to perform an unauthorized operation". There's currently no way to make that same call via a PowerShell cmdlet directly, and I figured this was some internal API originally and couldn't be used. So seeing your repo was a game changer for me.

Do you have any pointers or tips? Happy to take this off Github, thought this was worth a shot. Sorry and thanks again.
![image](https://user-images.githubusercontent.com/15617006/223261141-b5bbe2e3-8db4-4773-a3d1-c705d22a479c.png)

**Comment by jwelker9** [comment]
jwelker9(at)gmail(dot)(com) if you see this, thanks!

**Comment by ricmik** [comment]
Hi @jwelker9,

Great to see others doing work to automate PIM :)

You are sure that you are fetching the correct token for the api.azrbac.mspim.azure.com endpoint?
Can you do anything else with this token (Azure Resources / Non-Azure Resources)?

I'm currently on paternity leave so it's not the easiest time for me to try this out, but I'll see what I can do in the upcoming days.

**Comment by ricmik** [comment]
Hi @jwelker9,

It seems like the issue with generating the file was an incorrect audience in the token. When I had a look at the token used in the Azure portal, I saw that the audience was '01fc33a7-78ba-4d2f-a4b7-768e336e890e' (MS-PIM).

By fetching a new token with this GUID as the ResourceUrl, the file was generated successfully.

```powershell
$pimAPIToken = Get-AzAccessToken -ResourceUrl '01fc33a7-78ba-4d2f-a4b7-768e336e890e' 
        
$headers = @{
    "Authorization" = "Bearer {0}" -f ($($pimAPIToken.Token))
}
        
$APIUri = 'https://api.azrbac.mspim.azure.com/api/v2/privilegedAccess/azureResources/roleAssignments/exportWithChildren'

$parameters = @{
    '$expand' = 'subject,roleDefinition($expand=resource)'
    '$filter' = "(roleDefinition/resource/id eq '60dab533-dcac-4d45-bf58-fcba72024d07')"
}
$result = Invoke-WebRequest -Headers $headers -Uri $APIUri  -Method Get -Body $parameters 
```
